"""Prompt + game-code rendering for Pipeline 1.

`render_game_code` fills the Daytona game template from the game spec. Keeping this
separate from the spec logic means the LLM-authored code path is swappable without
touching ordering rules.
"""

from __future__ import annotations

from typing import Any

# The template library lives in the Daytona snapshot; here we render the entrypoint
# that binds the spec's levels to the template's mechanic renderers.
GAME_ENTRYPOINT_TEMPLATE = '''\
# Auto-generated by ADHDQuest Pipeline 1. Do not edit by hand.
import json
from templates import build_game

with open("game_spec.json") as f:
    SPEC = json.load(f)

if __name__ == "__main__":
    build_game(SPEC).run()
'''


def render_game_code(spec: dict[str, Any]) -> str:
    """Return the game.py source for this spec.

    For the deterministic path we emit a thin entrypoint that delegates to the
    template library. A stronger implementation asks the game-spec LLM to author
    per-level logic; the critic loop in daytona_node repairs runtime errors.
    """
    return GAME_ENTRYPOINT_TEMPLATE


GAME_SPEC_SYSTEM_PROMPT = """\
You are the ADHDQuest game designer. Given a list of tagged homework questions,
prior behavioral memory for this specific child, and a grade-level curriculum
prerequisite map, produce a game spec that:
  - orders levels easy -> hard, but front-loads topics the child historically
    struggles with so they land before attention fatigue,
  - assigns a game mechanic per topic and never repeats a mechanic more than twice
    in a row,
  - inserts low-effort "breather" checkpoint levels every (baseline/3) minutes,
  - configures a fail_threshold of 3 for replan triggers.
Return only JSON matching game_spec.schema.json.
"""
